# @package _global_

models:
  decoder:
    _target_: ${decoder_path}.UNet
    in_channels: [128, 256, 512, 1024] # [24, 40, 112, 320] # [96, 192, 384, 768] # [24, 40, 112, 320] # [256, 512, 1024, 2048] # [64, 128, 256, 512]  # Input layer channel
    strides: [4, 8, 16, 32]           # Input layer scale
    inner_channels: 256 # 256               # Hidden layer channel
    output_channels: 64 # 64               # output layer channel
    bias: False