# @package _global_

models:
  encoder:
    _target_: ${encoder_path}.TimmBackbone
    model_name: convnext_base.fb_in22k_ft_in1k_384 # 'efficientnet_b0'
    select_features: [0, 1, 2, 3] #[1, 2, 3, 4]            # Output layer
    pretrained: true
