# @package _global_

dataset_base_path: "/data/datasets/"   # Change your path

datasets:
  train_dataset1:
    _target_: ${dataset_path}.OCRDataset
    image_path: ${dataset_base_path}images/train
    annotation_path: ${dataset_base_path}jsons/train.json
    bbox_path : null
    transform: ${transforms.train_transform1}
  train_dataset2:
    _target_: ${dataset_path}.OCRDataset
    image_path: ${dataset_base_path}images/train
    annotation_path: ${dataset_base_path}jsons/train.json
    bbox_path : null
    transform: ${transforms.train_transform2}
  train_dataset3:
    _target_: ${dataset_path}.OCRDataset
    image_path: ${dataset_base_path}images/train
    annotation_path: ${dataset_base_path}jsons/train.json
    bbox_path : null
    transform: ${transforms.train_transform3}
  val_dataset:
    _target_: ${dataset_path}.OCRDataset
    image_path: ${dataset_base_path}images/val
    annotation_path: ${dataset_base_path}jsons/val.json
    bbox_path : null
    transform: ${transforms.val_transform}
  test_dataset:
    _target_: ${dataset_path}.OCRDataset
    image_path: ${dataset_base_path}images/val
    annotation_path: ${dataset_base_path}jsons/val.json
    bbox_path : null
    transform: ${transforms.test_transform}
  predict_dataset:
    _target_: ${dataset_path}.OCRDataset
    image_path: ${dataset_base_path}images/test
    annotation_path: null
    bbox_path : ${dataset_base_path}jsons/test_bbox.json
    transform: ${transforms.test_transform}

transforms:
  train_transform1:
    _target_: ${dataset_path}.DBTransforms
    transforms:
      - _target_: albumentations.LongestMaxSize
        max_size: 640
        p: 1.0
      - _target_: albumentations.PadIfNeeded
        min_width: 640
        min_height: 640
        border_mode: 0
        p: 1.0
      - _target_: albumentations.CLAHE
        p: 1.0
        clip_limit: 5
        tile_grid_size: [2, 5]
      # - _target_: albumentations.HorizontalFlip
      #   p: 0.5
      - _target_: albumentations.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        # mean: [0.133, 0.141, 0.148]
        # std: [0.448, 0.406, 0.368]
    keypoint_params:
      _target_: albumentations.KeypointParams
      format: 'xy'
      remove_invisible: True
  train_transform2:
    _target_: ${dataset_path}.DBTransforms
    transforms:
      - _target_: albumentations.LongestMaxSize
        max_size: 640
        p: 1.0
      - _target_: albumentations.PadIfNeeded
        min_width: 640
        min_height: 640
        border_mode: 0
        p: 1.0
      - _target_: albumentations.CLAHE
        p: 1.0
        clip_limit: 5
        tile_grid_size: [2, 5]
      - _target_: albumentations.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        # mean: [0.133, 0.141, 0.148]
        # std: [0.448, 0.406, 0.368]
    keypoint_params:
      _target_: albumentations.KeypointParams
      format: 'xy'
      remove_invisible: True
  train_transform3:
    _target_: ${dataset_path}.DBTransforms
    transforms:
      - _target_: albumentations.LongestMaxSize
        max_size: 640
        p: 1.0
      - _target_: albumentations.PadIfNeeded
        min_width: 640
        min_height: 640
        border_mode: 0
        p: 1.0
      - _target_: albumentations.HueSaturationValue
        p: 1.0
        hue_shift_limit: [10, 30]
        sat_shift_limit: [10, 30]
        val_shift_limit: [10, 30]
      - _target_: albumentations.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        # mean: [0.133, 0.141, 0.148]
        # std: [0.448, 0.406, 0.368]
    keypoint_params:
      _target_: albumentations.KeypointParams
      format: 'xy'
      remove_invisible: True
  val_transform:
    _target_: ${dataset_path}.DBTransforms
    transforms:
      - _target_: albumentations.LongestMaxSize
        max_size: 640
        p: 1.0
      - _target_: albumentations.PadIfNeeded
        min_width: 640
        min_height: 640
        border_mode: 0
        p: 1.0
      - _target_: albumentations.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        # mean: [0.133, 0.141, 0.148]
        # std: [0.448, 0.406, 0.368]
    keypoint_params:
      _target_: albumentations.KeypointParams
      format: 'xy'
      remove_invisible: True
  test_transform:
    _target_: ${dataset_path}.DBTransforms
    transforms:
      - _target_: albumentations.LongestMaxSize
        max_size: 640
        p: 1.0
      - _target_: albumentations.PadIfNeeded
        min_width: 640
        min_height: 640
        border_mode: 0
        p: 1.0
      - _target_: albumentations.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        # mean: [0.133, 0.141, 0.148]
        # std: [0.448, 0.406, 0.368]
    keypoint_params:
      _target_: albumentations.KeypointParams
      format: 'xy'
      remove_invisible: True
  predict_transform:
    _target_: ${dataset_path}.DBTransforms
    transforms:
      - _target_: albumentations.LongestMaxSize
        max_size: 640
        p: 1.0
      - _target_: albumentations.PadIfNeeded
        min_width: 640
        min_height: 640
        border_mode: 0
        p: 1.0
      - _target_: albumentations.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        # mean: [0.133, 0.141, 0.148]
        # std: [0.448, 0.406, 0.368]
    keypoint_params: null

dataloaders:
  train_dataloader:
    batch_size: 4
    shuffle: True
    num_workers: 4
  val_dataloader:
    batch_size: 4
    shuffle: False
    num_workers: 4
  test_dataloader:
    batch_size: 4
    shuffle: False
    num_workers: 4
  predict_dataloader:
    batch_size: 1
    shuffle: False
    num_workers: 4

collate_fn:
  _target_: ${dataset_path}.DBCollateFN
  shrink_ratio: 0.4
  thresh_min: 0.3
  thresh_max: 0.7
