# @package _global_

# https://arxiv.org/pdf/1911.08947.pdf 참조

models:
  head:
    _target_: ${head_path}.DBHead
    in_channels: 256                 # Input layer channel
    upscale: 4                       # Output layer scale factor
    k: 50                            # The amplifying factor
    bias: False                      # Use bias or not in LayerNorm
    smooth: False                    # Use smooth or not in Upsample
    postprocess:
      thresh: 0.3                    # Binarization threshold
      box_thresh: 0.47                # Detection Box threshold
      max_candidates: 500            # Limit the number of detection boxes
      use_polygon: True             # Detection Box Type (QUAD or POLY)
    asf: True                       # Adaptive scale fusion module
