defaults:
  - _self_
  - preset:
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

seed: 42
exp_name: "convnext_base_384_dbnet++_crop_usePolygon_epoch20_his_before_crop"
project_name: "OCRProject"

wandb: False
exp_version: "v1.0"

checkpoint_path: null
